language: minimal
dist: bionic

services:
  - docker

env:
  matrix:
    - ARCH=amd64 DIST=jessie
    - ARCH=amd64 DIST=stretch
    - ARCH=amd64 DIST=buster
    - ARCH=armhf DIST=jessie
    - ARCH=armhf DIST=stretch
    - ARCH=armhf DIST=buster
    - ARCH=arm64 DIST=stretch
    - ARCH=arm64 DIST=buster

script:
  - >
    sudo apt-get update &&
    sudo apt-get install -y binfmt-support qemu-user-static &&
    sudo systemctl restart binfmt-support
  - make ARCH=${ARCH} DIST=${DIST}

after_success:
  - >
    if [ "${TRAVIS_BRANCH}" == "master" ]; then
      make upload
        ARCH=${ARCH}
        DIST=${DIST}
        DOCKER_USERNAME=${DOCKER_USERNAME}
        DOCKER_PASSWORD=${DOCKER_PASSWORD};
    fi
