language: minimal
dist: bionic

services:
  - docker

env:
  matrix:
    - ARCH=amd64 DIST=jessie
    - ARCH=amd64 DIST=stretch
    - ARCH=armhf DIST=jessie
    - ARCH=armhf DIST=stretch

script:
  - ARCH=${ARCH} DIST=${DIST} make
